spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
    show-sql: false
  threads:
    executor:
      pool:
        max-size: 50
        core-size: 50
        queue-capacity: 100

server:
  tomcat:
    threads:
      max: 50
      min-spare: 50

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    ex.demo: DEBUG
